name: Put name here
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: false

sass:
  style: :compressed

# This script is used to fix the missing promise library bug that happens in IE
scripts: assets/js/es6-promise-auto-min.js

# Author/Organization info to be displayed in the templates
author:
  name: Put name here
  url: Put url here

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/LogoFile
logoalt: Logo alternative
# To expand all navigation bar entries by default, set this property to true:
expand_nav: false

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Navigation Title
  internal: true
- text: Subheading
  url: Subheading/
  internal: true
  children:
  - text: Child
    url: Child/
    internal: true

repos:
- name: Put name here
  description: Main repository
  url: Url to git

back_link:
  url:
  text:

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  # skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
